### ISSUE TITLE
@atomic not applicable for the Class Based Views

### ISSUE THREAD

**Issue by mpyatishev** [aio-libs/aiojobs#21]
```
File "/home/max/work/hc_market/env/lib/python3.6/site-packages/aiohttp/web_urldispatcher.py", line 753, in __await__
    return (yield from self.__iter__())
File "/home/max/work/hc_market/env/lib/python3.6/site-packages/aiohttp/web_urldispatcher.py", line 748, in __iter__
    resp = yield from method()
File "/home/max/work/hc_market/env/lib/python3.6/site-packages/aiojobs/aiohttp.py", line 28, in wrapper
    job = await spawn(request, coro(request))
File "/home/max/work/hc_market/env/lib/python3.6/site-packages/aiojobs/aiohttp.py", line 22, in spawn
    return await get_scheduler(request).spawn(coro)
File "/home/max/work/hc_market/env/lib/python3.6/site-packages/aiojobs/aiohttp.py", line 10, in get_scheduler
    scheduler = get_scheduler_from_app(request.app)
AttributeError: 'Test' object has no attribute 'app'
```

**Comment by asvetlov** [comment]
Yes, it is true.
Would you make a pull request?
The task is relative easy and straightforward.

**Comment by mpyatishev** [comment]
Well, I'll try.

**Comment by asvetlov** [comment]
Fixed by #22

**Comment by xlionx** [comment]
@asvetlov It still does not work properly, `coro` gets request object instead view object. And I don't have access to class attributes inside view, because `self = request`
